const randomNumbers = (max, min) => {
  let random = Math.floor(Math.random() * (max - min + 1) + min);
  return random;
};

// ---------------------------------------------------------

/*4. Ejercicio
Escribe un programa que simula un
 semáforo. El semáforo estará controlado por
una variable “centinela” llamada “isGreen”.
Si el semáforo está verde, mostrar por consola:
“Cross the road”, en caso contrario mostrar:
“Please wait”.*/

// start the arrow func.
const a1e4 = () => {
  // set the Array constant isGreen with colors values
  const isGreen = [
    "yellow",
    "yellow",
    "yellow",
    "yellow",
    "red",
    "red",
    "red",
    "red",
    "red",
    "green",
  ];
  // create a looping true to read the colors inside the array
  for (let i = 0; i < isGreen.length; i++) {
    // this const color is to save the array values readed
    const color = isGreen[i];
    // if statement to check the traffic color and log a message
    if (isGreen[i] === "green") {
      console.log("Cross the road");
    } else if (isGreen[i] === "red") {
      console.log(`Please wait (${i})`);
    } else {
      console.log(`Be cautious (${i})`);
    }
  }
};
// call the arrow function a1e4()
// a1e4();

// ---------------------------------------------------------

/*10. Ejercicio
Investiga el objeto Math, y genera 2 números aleatorios, entre 1 y 6, 
para simular un juego de dados. Comprueba los resultados obtenidos y
 muestra por consola el ganador. Por ejemplo: 
“Player 1 wins!”, o “draw”, en caso de empate.*/

// start the arrow func.
const a1e10 = () => {
  //  Defining function which returns a random number between min and max
  function randomNumber(min, max) {
    /*the Math.floor method round the number (integer) which come from
      Math.random (float )and generate a number and multiply max & min 
      and then adding min to get a random integer between max and min*/
    return Math.floor(Math.random() * (max - min + 1) + min);
  }
  /*the variables store the random numbers generated by calling 
  the randomNumber(1, 6) and logged the variables to the console */
  let num1 = randomNumber(1, 6);
  let num2 = randomNumber(1, 6);
  console.log(num1);
  console.log(num2);
  // comparing the two numbers and display the winner or a draw
  if (num1 > num2) {
    console.log("Player 1 wins!");
  } else if (num1 < num2) {
    console.log("Player 2 wins!");
  } else {
    console.log("Draw");
  }
};
// call the arrow function a1e10
a1e10();

// ---------------------------------------------------------
